import React, { useState, useEffect } from 'react';
import { ApiStatus } from '../types';
import type { GeneratedContent } from '../types';
import { DownloadIcon } from './icons/DownloadIcon';
import { ZoomInIcon } from './icons/ZoomInIcon';
import { EmptyState } from './EmptyState';
import { ImageIcon } from './icons/ImageIcon';

const loadingMessages = [
  "正在召唤 AI 创作精灵...",
  "正在用像素绘画...",
  "魔法正在发生，请稍候...",
  "正在融合创意与代码...",
  "高品质的艺术创作需要一点耐心！",
];

const LoadingSpinner: React.FC = () => {
  const [message, setMessage] = useState(loadingMessages[0]);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setMessage(prevMessage => {
        const currentIndex = loadingMessages.indexOf(prevMessage);
        const nextIndex = (currentIndex + 1) % loadingMessages.length;
        return loadingMessages[nextIndex];
      });
    }, 2500);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <div className="flex flex-col items-center justify-center gap-4 text-center">
      <div className="w-16 h-16 border-4 border-dashed rounded-full animate-spin border-indigo-400"></div>
      <p className="text-lg text-gray-300 font-semibold mt-2">AI 正在思考...</p>
      <p className="text-sm text-gray-400 transition-opacity duration-500">{message}</p>
    </div>
  );
};

const ErrorDisplay: React.FC<{ message: string }> = ({ message }) => (
  <div className="p-4 border-l-4 border-red-500 bg-red-900/20 rounded-r-lg max-w-md mx-auto">
    <h3 className="font-bold text-red-400">生成失败</h3>
    <p className="text-red-300 text-sm mt-1">{message}</p>
  </div>
);

interface GeneratedImageDisplayProps {
  status: ApiStatus;
  error: string | null;
  content: GeneratedContent | null;
  onPreviewClick: (url: string) => void;
}

export const GeneratedImageDisplay: React.FC<GeneratedImageDisplayProps> = ({ status, error, content, onPreviewClick }) => {
  
  const handleDownload = () => {
    if (!content?.imageUrl) return;
    const link = document.createElement('a');
    link.href = content.imageUrl;
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    link.download = `ai-generated-${timestamp}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const renderContent = () => {
    switch (status) {
      case ApiStatus.Loading:
        return <LoadingSpinner />;
      case ApiStatus.Error:
        return error ? <ErrorDisplay message={error} /> : null;
      case ApiStatus.Success:
        if (content?.imageUrl) {
          return (
             <div className="w-full h-full flex flex-col items-center justify-center gap-4 p-4">
                <div className="flex-grow w-full flex items-center justify-center relative group min-h-0">
                    <img 
                        src={content.imageUrl} 
                        alt="Generated by AI" 
                        className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
                        style={{ maxHeight: 'calc(100vh - 12rem)'}}
                    />
                    <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center gap-4 rounded-lg">
                        <button onClick={() => onPreviewClick(content.imageUrl!)} className="flex items-center gap-2 px-5 py-2.5 text-sm font-bold text-white bg-gray-700/80 rounded-lg shadow-lg hover:bg-gray-600/80 backdrop-blur-sm transition-all transform hover:scale-105" aria-label="预览">
                            <ZoomInIcon className="w-5 h-5"/>
                            <span>预览</span>
                        </button>
                        <button onClick={handleDownload} className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 text-white font-bold rounded-lg text-sm shadow-lg hover:bg-indigo-500 backdrop-blur-sm transition-all transform hover:scale-105" aria-label="下载">
                            <DownloadIcon className="w-5 h-5"/>
                            <span>下载</span>
                        </button>
                    </div>
                </div>
                {content.text && (
                  <div className="flex-shrink-0 w-full flex justify-center mt-2">
                      <p className="text-center text-gray-400 bg-gray-900/50 p-2 rounded-md text-xs w-full max-w-lg">
                          {content.text}
                      </p>
                  </div>
                )}
            </div>
          );
        }
        return null;
      case ApiStatus.Idle:
      default:
        return (
          <div className="w-full h-full flex items-center justify-center">
            <EmptyState
              icon={<ImageIcon className="w-16 h-16 text-gray-700" />}
              text="您的作品将在这里展示"
              subtext="在右侧输入提示词，然后点击生成按钮"
            />
          </div>
        );
    }
  };

  return (
    <div className="w-full h-full flex items-center justify-center">
      {renderContent()}
    </div>
  );
};